#!/bin/bash

function wait_for_ssh {
	HOST_STRING="$1"
	REVERSE=0
	[ "$2" ] && REVERSE=1

	# wait loop
	set +e
	CONTINUE=1
	while [ $CONTINUE -eq 1 ]; do
		ssh -o StrictHostKeyChecking=no -o ConnectTimeout=600 -o ConnectionAttempts=1000 "$HOST_STRING" -- hostname
		RETVAL=$?
		[ ! "$RETVAR" ] && RETVAR=0

		if [ $REVERSE -eq 0 -a $RETVAR -eq 0 ]; then
			CONTINUE=0
		elif [ $REVERSE -eq 0 -a $RETVAR -ne 0 ]; then
			CONTINUE=1
		elif [ $REVERSE -eq 1 -a $RETVAR -eq 0 ]; then
			CONTINUE=1
		else
			CONTINUE=0
		fi

		[ $CONTINUE -ne 0 ] && sleep 1
	done
	set -e
}


set -x
set -e

if [ -z "$1" ]; then
	echo "Missing TTSERVER_BRANCH parameter."
	echo
	echo "Example: ./ttvagrant develop tttest66 2166"
	exit 1
fi

if [ -z "$2" ]; then
	echo "Missing TTSERVER_PREFIX parameter."
	exit 1
fi

if [ -z "$3" ]; then
	echo "Missing TTSERVER_PORT parameter."
	exit 1
fi

if [ -z "$VAGRANT_DIR" ]; then
	VAGRANT_DIR=/home/vagrant/taptinder-testing/fedora-21
fi

SRC_DIR=`pwd`

TTSERVER_BRANCH="$1"
TTSERVER_PREFIX="$2"
TTSERVER_PORT="$3"


cd $VAGRANT_DIR
mkdir server-$TTSERVER_PREFIX.taptinder.org
cd server-$TTSERVER_PREFIX.taptinder.org/
ln -s $VAGRANT_DIR/Vagrantfile .
ls -al

vagrant up


wait_for_ssh "root@server-$TTSERVER_PREFIX.taptinder.org"

# todo
sleep 3

rsync -ave "ssh -o StrictHostKeyChecking=no" $SRC_DIR/setup-ttserver-p*.sh root@server-$TTSERVER_PREFIX.taptinder.org:/root/
ssh -oStrictHostKeyChecking=no root@server-$TTSERVER_PREFIX.taptinder.org -- /root/setup-ttserver-p1.sh $TTSERVER_BRANCH $TTSERVER_PREFIX $TTSERVER_PORT

# shutdown -r now
ssh -oStrictHostKeyChecking=no root@server-$TTSERVER_PREFIX.taptinder.org -- shutdown -r now || :

# todo
sleep 10
#wait_for_ssh "root@server-$TTSERVER_PREFIX.taptinder.org" reverse

wait_for_ssh "root@server-$TTSERVER_PREFIX.taptinder.org"

ssh -t -oStrictHostKeyChecking=no root@server-$TTSERVER_PREFIX.taptinder.org -- /root/setup-ttserver-p2.sh $TTSERVER_BRANCH $TTSERVER_PREFIX $TTSERVER_PORT
